const config = {
    attributeGroups: [
        '$ANGULAR_STRUCTUAL_DIRECTIVE',
        '^\\[ng(?!(Class|Style||Model)).*',
        '$ANGULAR_ELEMENT_REF',
        'pTemplate',
        '$ID',
        '^\\[?id\\]?$',
        '^\\[?inputId\\]?$',
        '$CLASS',
        '^\\[?class\\]?$',
        '^\\[?class\\.?',
        '^\\[?ngClass\\]?$',
        '^\\[?style\\]?$',
        '^\\[?style\\.',
        '^\\[?ngStyle\\]?$',
        'styleClass\\b',
        '$ANGULAR_TWO_WAY_BINDING',
        '^\\[\\(?ngModel',
        'formControlName\\b',
        '^\\[?key\\]?$',
        '^\\[?value\\]?$',
        '^\\[?selection\\]?$',
        '^\\[?options\\]?$',
        '^\\[?optionValue\\]?$',
        '^\\[?optionLabel\\]?$',
        '^\\[?autoDisplayFirst\\]?$',
        '^\\[?scrollable\\]?$',
        '^\\[?virtualScrollItemSize\\]?$',
        '^\\[?virtualScrollDelay\\]?$',
        '^\\[?virtualScrollOptions\\]?$',
        '^\\[?scrollHeight\\]?$',
        '^\\[?filter\\]?$',
        '^\\[?filterBy\\]?$',
        '$DEFAULT',
        '^\\[?type\\]?$',
        '^\\[?appendTo\\]?$',
        'pTooltip',
        'pInputText',
        '^\\[?readonly\\]?$',
        '^\\[?disabled\\]?$',
        '^\\[?innerHTML\\]?$',
        '^\\[?dateFormat\\]?$',
        'placeholder',
        '^\\[?filterPlaceholder\\]?$',
        '^\\[?label\\]?$',
        '^\\[?emptyFIlterMessage\\]?$',
        '^\\[?emptyMessage\\]?$',
        '$ANGULAR_OUTPUT'
    ],
    bracketSameLine: true,
    bracketSpacing: true,
    endOfLine: 'crlf',
    plugins: ['prettier-plugin-sort-json', 'prettier-plugin-organize-attributes'],
    printWidth: 120,
    semi: true,
    singleQuote: true,
    tabWidth: 4,
    trailingComma: 'none'
};

module.exports = config;
