import { UiManagedApplications } from '../interfaces/ui-managed-applications.interface';

export const MANAGE_STUB: UiManagedApplications = {
    maxNameLength: 100,
    blackListApps: [
        'A180AG',
        'ai',
        'chrome',
        'firefox',
        'iexplore',
        'java',
        'javaw',
        'microsoftedge',
        'msedge',
        'msedgewebview2',
        'plugin-container'
    ],
    apps: [
        {
            identifiers: ['bobo'],
            type: 'WindowsApp',
            id: 2432,
            appName: 'Pini_test',
            enabled: true,
            version: 5,
            isOOtB: false,
            lastMod: 1675857017000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: [],
            type: 'WindowsApp',
            id: 2944,
            appName: 'application event tomer',
            enabled: true,
            version: 2,
            isOOtB: false,
            lastMod: 1689781875000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['cefsharp.browsersubprocess', 'pbidesktop'],
            type: 'WindowsApp',
            id: 2433,
            appName: 'Power BI',
            enabled: true,
            version: 5,
            isOOtB: false,
            lastMod: 1675857017000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: [],
            type: 'WindowsApp',
            id: 2434,
            appName: 'PowerPoint 365 Testing',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675857017000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 6,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['ppm'],
            type: 'WindowsApp',
            id: 2435,
            appName: 'PPM Desktop',
            enabled: true,
            version: 5,
            isOOtB: false,
            lastMod: 1675857017000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['msmpeng', 'sgrmbroker'],
            type: 'WindowsApp',
            id: 2436,
            appName: 'protectedPRC',
            enabled: true,
            version: 5,
            isOOtB: false,
            lastMod: 1675857018000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['www.aptimize.com', 'www.aptimize.com/blog'],
            type: 'WebApp',
            id: 2564,
            appName: 'aptimize',
            enabled: true,
            version: 4,
            isOOtB: false,
            lastMod: 1679948855000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['rally1.rallydev.com'],
            type: 'WebApp',
            id: 2437,
            appName: 'Rally - ראלי',
            enabled: true,
            version: 4,
            isOOtB: false,
            lastMod: 1675857018000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 23,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['com.zerista.rvbdpartnersummit'],
            type: 'MobileApp',
            id: 2438,
            appName: 'RB Events (Partner Summit)',
            enabled: true,
            version: 4,
            isOOtB: false,
            lastMod: 1675857019000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 23,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['riverbed.com'],
            type: 'WebApp',
            id: 2441,
            appName: 'Riverbed',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1728995167000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 7,
            rollout: 'MultipleGroups',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: [],
            type: 'WindowsApp',
            id: 2314,
            appName: '_idh',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675855965000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['portalqa.rpm.riverbedlab.net'],
            type: 'WebApp',
            id: 2442,
            appName: 'Riverbed Portal',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675857019000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['7zFM'],
            type: 'WindowsApp',
            id: 2315,
            appName: '7-zip',
            enabled: true,
            version: 5,
            isOOtB: false,
            lastMod: 1675855981000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['rvbdtech.sharepoint.com'],
            type: 'WebApp',
            id: 2443,
            appName: 'Riverbed Sharepoint',
            enabled: true,
            version: 4,
            isOOtB: false,
            lastMod: 1675857020000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 4,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['10bis'],
            type: 'WindowsApp',
            id: 2316,
            appName: '10bis Executable',
            enabled: true,
            version: 4,
            isOOtB: false,
            lastMod: 1675856028000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['ru'],
            type: 'WebApp',
            id: 2444,
            appName: 'RU',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675857020000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['10*.co.il', '10bis.co.il'],
            type: 'WebApp',
            id: 2317,
            appName: '10bis',
            enabled: true,
            version: 4,
            isOOtB: false,
            lastMod: 1675856040000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 11,
            rollout: 'Custom',
            assignment: {
                includes: {
                    names: ['All', 'Assistant SW Updates Active'],
                    hasMore: false
                },
                excludes: null
            },
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['saas-monitor.aternity.com'],
            type: 'WebApp',
            id: 2445,
            appName: 'SaaS monitor',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675857020000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['aha.io'],
            type: 'WebApp',
            id: 2318,
            appName: 'Aha',
            enabled: true,
            version: 2,
            isOOtB: false,
            lastMod: 1675856048000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: [
                'login.salesforce.com',
                'na3.salesforce.com',
                'na32.salesforce.com',
                'na57.salesforce.com',
                'na61.salesforce.com',
                'riverbed.my.salesforce.com',
                'success.salesforce.com',
                'tableau.my.salesforce.com'
            ],
            type: 'WebApp',
            id: 2446,
            appName: 'Salesforce',
            enabled: true,
            version: 4,
            isOOtB: false,
            lastMod: 1675857020000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 12,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['www.aliexpress.com'],
            type: 'WebApp',
            id: 2319,
            appName: 'AliExpress',
            enabled: true,
            version: 4,
            isOOtB: false,
            lastMod: 1675856055000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['ven03656.service-now.com'],
            type: 'WebApp',
            id: 2447,
            appName: 'Service Now',
            enabled: true,
            version: 4,
            isOOtB: false,
            lastMod: 1675857021000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['com'],
            type: 'WebApp',
            id: 2320,
            appName: 'All web Browsing',
            enabled: false,
            version: 3,
            isOOtB: false,
            lastMod: 1675856233000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['www.servicenow.com'],
            type: 'WebApp',
            id: 2448,
            appName: 'ServiceNow',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675857021000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['applications.testharness', 'testharness'],
            type: 'WindowsApp',
            id: 2321,
            appName: 'Allscripts',
            enabled: true,
            version: 6,
            isOOtB: false,
            lastMod: 1675856233000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 235,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['SF1299728'],
            type: 'WindowsApp',
            id: 2449,
            appName: 'SF1299728 Logoff duration',
            enabled: true,
            version: 6,
            isOOtB: false,
            lastMod: 1675857021000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 5,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: [],
            type: 'WindowsApp',
            id: 2450,
            appName: 'Shay-Test',
            enabled: true,
            version: 4,
            isOOtB: false,
            lastMod: 1675857021000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['Shedim.com'],
            type: 'WebApp',
            id: 2451,
            appName: 'Shedim (OnApp)',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675857022000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 3,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['riverbedsko.zerista.com'],
            type: 'WebApp',
            id: 2452,
            appName: 'SKO 2018 Web',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675857022000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 7,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['Software_Reporter_Tool'],
            type: 'WindowsApp',
            id: 2453,
            appName: 'Software_Reporter_Tool',
            enabled: true,
            version: 5,
            isOOtB: false,
            lastMod: 1675857022000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: [],
            type: 'WindowsApp',
            id: 2454,
            appName: 'Spanish Word',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675857022000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['sqldeveloper', 'sqldeveloper64', 'sqldeveloper64w'],
            type: 'WindowsApp',
            id: 2455,
            appName: 'SQL Developer',
            enabled: true,
            version: 6,
            isOOtB: false,
            lastMod: 1675857022000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 6,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['com.aternity.training'],
            type: 'MobileApp',
            id: 2328,
            appName: 'Aternity Training',
            enabled: true,
            version: 6,
            isOOtB: false,
            lastMod: 1675856450000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 22,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['support.microsoft.com'],
            type: 'WebApp',
            id: 2456,
            appName: 'support.microsoft.com',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675857022000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['cost-utest.lab.aternity.com'],
            type: 'WebApp',
            id: 2329,
            appName: 'Aternity uTest',
            enabled: true,
            version: 6,
            isOOtB: false,
            lastMod: 1679949766000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 15,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['com.aternity.automatedtest'],
            type: 'MobileApp',
            id: 2330,
            appName: 'AutomatedTest',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675856450000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['test'],
            type: 'WindowsApp',
            id: 2332,
            appName: 'automation-test',
            enabled: true,
            version: 5,
            isOOtB: false,
            lastMod: 1675856450000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['de.wikipedia.org'],
            type: 'WebApp',
            id: 2340,
            appName: 'de.wikipedia.org',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675856542000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['Test1'],
            type: 'WindowsApp',
            id: 6564,
            appName: 'Test2',
            enabled: true,
            version: 2,
            isOOtB: false,
            lastMod: 1734345387000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 3,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['Acrobat', 'acrord32', 'acrord64', 'AdobeReader'],
            type: 'WindowsApp',
            id: 421,
            appName: 'Acrobat Reader',
            enabled: true,
            version: 3,
            isOOtB: true,
            lastMod: 1623195648000,
            deletable: false,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 5,
            rollout: 'MultipleGroups',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['10.77.225.106/yoni/de14565'],
            type: 'WebApp',
            id: 2341,
            appName: 'de14565',
            enabled: true,
            version: 4,
            isOOtB: false,
            lastMod: 1675856542000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['Test10'],
            type: 'WindowsApp',
            id: 6565,
            appName: 'Test11',
            enabled: true,
            version: 2,
            isOOtB: false,
            lastMod: 1734346303000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 3,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['qa-kb.lab.aternity.com/Yoni'],
            type: 'WebApp',
            id: 2342,
            appName: 'DE18824',
            enabled: true,
            version: 4,
            isOOtB: false,
            lastMod: 1675856542000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 3,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['www.debka.co.il/search'],
            type: 'WebApp',
            id: 2343,
            appName: 'Debka search',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675856543000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['deletethis.com'],
            type: 'WebApp',
            id: 2344,
            appName: 'DeleteThis',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675856543000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['chrome', 'Google Chrome'],
            type: 'WindowsApp',
            id: 426,
            appName: 'Chrome',
            enabled: true,
            version: 1,
            isOOtB: true,
            lastMod: 1623195650000,
            deletable: false,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['DEM-5182.com'],
            type: 'WebApp',
            id: 2346,
            appName: 'DEM-5182',
            enabled: true,
            version: 4,
            isOOtB: false,
            lastMod: 1675856543000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 11,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: [
                'atmgr',
                'CiscoCollabHost',
                'CiscoWebExStart',
                'ptoneclk',
                'ptwbxoni',
                'teamshvdagent',
                'WebexHost',
                'webexmta'
            ],
            type: 'WindowsApp',
            id: 427,
            appName: 'Cisco Webex',
            enabled: true,
            version: 3,
            isOOtB: true,
            lastMod: 1623195650000,
            deletable: false,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 6,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['127.0.0.1:8000'],
            type: 'WebApp',
            id: 2347,
            appName: 'DEM-7110',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675856544000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['StartStop'],
            type: 'WindowsApp',
            id: 2348,
            appName: 'DEM-8028',
            enabled: true,
            version: 6,
            isOOtB: false,
            lastMod: 1675856544000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 3,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['DEM-8813.com'],
            type: 'WebApp',
            id: 2349,
            appName: 'DEM-8813',
            enabled: true,
            version: 4,
            isOOtB: false,
            lastMod: 1675856544000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 7,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['com.aternity.demo', 'com.aternity.mobilesaasdemo'],
            type: 'MobileApp',
            id: 2351,
            appName: 'Demo',
            enabled: true,
            version: 2,
            isOOtB: false,
            lastMod: 1675856545000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['microsoftedge', 'msedge'],
            type: 'WindowsApp',
            id: 432,
            appName: 'Edge',
            enabled: true,
            version: 1,
            isOOtB: true,
            lastMod: 1623195653000,
            deletable: false,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['python'],
            type: 'WindowsApp',
            id: 2352,
            appName: 'Desktop App Simulator (Avi H)',
            enabled: true,
            version: 6,
            isOOtB: false,
            lastMod: 1675856545000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 3,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['iexplore'],
            type: 'WindowsApp',
            id: 433,
            appName: 'Internet Explorer',
            enabled: true,
            version: 2,
            isOOtB: true,
            lastMod: 1623195653000,
            deletable: false,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['nlnotes', 'notes', 'notes2'],
            type: 'WindowsApp',
            id: 434,
            appName: 'Lotus Notes',
            enabled: true,
            version: 2,
            isOOtB: true,
            lastMod: 1623195653000,
            deletable: false,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 8,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: [
                'DG Agent Manager V11',
                'DG Agent Manager V14',
                'DG Agent Manager V17',
                'dgagent',
                'DGAgentV17',
                'DgPrompt'
            ],
            type: 'WindowsApp',
            id: 2355,
            appName: 'Digital Guardian',
            enabled: true,
            version: 5,
            isOOtB: false,
            lastMod: 1675856545000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['DiscoveryAsMonitor'],
            type: 'WindowsApp',
            id: 2357,
            appName: 'DiscoveryAsMonitor',
            enabled: true,
            version: 6,
            isOOtB: false,
            lastMod: 1675856545000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 3,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['com.aternity.droidtestapp'],
            type: 'MobileApp',
            id: 2358,
            appName: 'DroidTestApp',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675856546000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 3,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['excel', 'Microsoft Excel'],
            type: 'WindowsApp',
            id: 439,
            appName: 'Microsoft Excel',
            enabled: true,
            version: 10,
            isOOtB: true,
            lastMod: 1623195655000,
            deletable: false,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 25,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['ebay.com'],
            type: 'WebApp',
            id: 2359,
            appName: 'ebay',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675856546000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['Microsoft OneNote', 'onenote', 'onenoteim', 'onenotem'],
            type: 'WindowsApp',
            id: 440,
            appName: 'Microsoft OneNote',
            enabled: true,
            version: 2,
            isOOtB: true,
            lastMod: 1623195657000,
            deletable: false,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['Microsoft Outlook', 'olk', 'outlook'],
            type: 'WindowsApp',
            id: 441,
            appName: 'Microsoft Outlook',
            enabled: true,
            version: 7,
            isOOtB: true,
            lastMod: 1623195657000,
            deletable: false,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 63,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['erez'],
            type: 'WindowsApp',
            id: 2361,
            appName: 'Erez',
            enabled: true,
            version: 5,
            isOOtB: false,
            lastMod: 1675856547000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['Microsoft PowerPoint', 'powerpnt'],
            type: 'WindowsApp',
            id: 442,
            appName: 'Microsoft PowerPoint',
            enabled: true,
            version: 6,
            isOOtB: true,
            lastMod: 1642997122000,
            deletable: false,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 21,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['facebook.com'],
            type: 'WebApp',
            id: 2362,
            appName: 'Facebook',
            enabled: true,
            version: 4,
            isOOtB: false,
            lastMod: 1675856547000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 9,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['Microsoft Project', 'winproj'],
            type: 'WindowsApp',
            id: 443,
            appName: 'Microsoft Project',
            enabled: true,
            version: 2,
            isOOtB: true,
            lastMod: 1623195664000,
            deletable: false,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 10,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: [],
            type: 'WindowsApp',
            id: 2363,
            appName: 'FireFox',
            enabled: false,
            version: 5,
            isOOtB: false,
            lastMod: 1675856547000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['ms-teams', 'Teams'],
            type: 'WindowsApp',
            id: 444,
            appName: 'Microsoft Teams',
            enabled: true,
            version: 4,
            isOOtB: true,
            lastMod: 1623195665000,
            deletable: false,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 9,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['Microsoft Word', 'winword'],
            type: 'WindowsApp',
            id: 445,
            appName: 'Microsoft Word',
            enabled: true,
            version: 6,
            isOOtB: true,
            lastMod: 1656991452000,
            deletable: false,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 21,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['mail.google.com/mail'],
            type: 'WebApp',
            id: 2365,
            appName: 'Gmail',
            enabled: true,
            version: 5,
            isOOtB: false,
            lastMod: 1675856597000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 31,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['google.com'],
            type: 'WebApp',
            id: 2366,
            appName: 'Google',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675856598000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 3,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['firefox', 'plugin-container'],
            type: 'WindowsApp',
            id: 447,
            appName: 'Mozilla Firefox',
            enabled: true,
            version: 2,
            isOOtB: true,
            lastMod: 1623195669000,
            deletable: false,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['google.co.il'],
            type: 'WebApp',
            id: 2367,
            appName: 'Google - Hebrew',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675856598000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 3,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['opera'],
            type: 'WindowsApp',
            id: 448,
            appName: 'Opera',
            enabled: true,
            version: 1,
            isOOtB: true,
            lastMod: 1623195669000,
            deletable: false,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['0.docs.google.com', 'docs.google.com'],
            type: 'WebApp',
            id: 2368,
            appName: 'Google docs',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675856598000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['translate.google.com'],
            type: 'WebApp',
            id: 2369,
            appName: 'Google Translate',
            enabled: false,
            version: 4,
            isOOtB: false,
            lastMod: 1675856598000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['safari'],
            type: 'WindowsApp',
            id: 450,
            appName: 'Safari',
            enabled: true,
            version: 1,
            isOOtB: true,
            lastMod: 1623195669000,
            deletable: false,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['www.google.co.il'],
            type: 'WebApp',
            id: 2370,
            appName: 'google.co.il',
            enabled: true,
            version: 4,
            isOOtB: false,
            lastMod: 1675856598000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['communicator', 'lync', 'lync99', 'Microsoft Lync', 'ucmapi'],
            type: 'WindowsApp',
            id: 451,
            appName: 'Skype for Business/Lync',
            enabled: true,
            version: 3,
            isOOtB: true,
            lastMod: 1623195669000,
            deletable: false,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 6,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['he.wikipedia.org'],
            type: 'WebApp',
            id: 2371,
            appName: 'he.wikipedia.org',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675856598000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['helpdesk.aternity.com'],
            type: 'WebApp',
            id: 2372,
            appName: 'helpDeskAternity',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675856598000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['CptHost', 'zoom'],
            type: 'WindowsApp',
            id: 453,
            appName: 'Zoom Meetings',
            enabled: true,
            version: 2,
            isOOtB: true,
            lastMod: 1623195670000,
            deletable: false,
            canBeEnabledDisabled: true,
            editable: false,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['hotmail.com'],
            type: 'WebApp',
            id: 2374,
            appName: 'hotmail.com',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675856598000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: [],
            type: 'WindowsApp',
            id: 2375,
            appName: 'IDH',
            enabled: true,
            version: 3,
            isOOtB: false,
            lastMod: 1675856598000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['aterdemo.c3.imonggo.com'],
            type: 'WebApp',
            id: 2376,
            appName: 'imonggo web store',
            enabled: true,
            version: 4,
            isOOtB: false,
            lastMod: 1675856598000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 5,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['notepad++'],
            type: 'WindowsApp',
            id: 6344,
            appName: 'Notepad++',
            enabled: true,
            version: 1,
            isOOtB: false,
            lastMod: 1732634556000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['idea', 'idea64'],
            type: 'WindowsApp',
            id: 2378,
            appName: 'IntelliJ',
            enabled: true,
            version: 5,
            isOOtB: false,
            lastMod: 1675856598000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['liferay'],
            type: 'WebApp',
            id: 2380,
            appName: 'Ithai-OnApp',
            enabled: true,
            version: 4,
            isOOtB: false,
            lastMod: 1675856599000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 4,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['apple.com'],
            type: 'WebApp',
            id: 5964,
            appName: 'Apple',
            enabled: true,
            version: 1,
            isOOtB: false,
            lastMod: 1728994258000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 3,
            rollout: 'TestGroup',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['telegraf'],
            type: 'WindowsApp',
            id: 6498,
            appName: 'telegraf',
            enabled: true,
            version: 1,
            isOOtB: false,
            lastMod: 1733326435000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['_ssh'],
            type: 'WindowsApp',
            id: 6499,
            appName: 'SSH',
            enabled: true,
            version: 1,
            isOOtB: false,
            lastMod: 1733326994000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 2,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['www.yoni-test.com'],
            type: 'WebApp',
            id: 6644,
            appName: 'Yoni-Test',
            enabled: true,
            version: 2,
            isOOtB: false,
            lastMod: 1734973900000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['hh'],
            type: 'WindowsApp',
            id: 6005,
            appName: 'calcJar',
            enabled: true,
            version: 2,
            isOOtB: false,
            lastMod: 1729600658000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 5,
            rollout: 'All',
            assignment: null,
            urls: null,
            isB2E: false
        },
        {
            identifiers: ['^peg_tool$'],
            type: 'WindowsApp',
            id: 6134,
            appName: 'peg_tool',
            enabled: true,
            version: 2,
            isOOtB: false,
            lastMod: 1734365128000,
            deletable: true,
            canBeEnabledDisabled: true,
            editable: true,
            activities: 1,
            rollout: 'Custom',
            assignment: {
                includes: {
                    names: ['C02CM28VMD6R-MAC', 'Mac OS'],
                    hasMore: false
                },
                excludes: null
            },
            urls: null,
            isB2E: false
        }
    ]
};
